os:
  - linux
language: csharp
solution: backoff/GBackoff/GBackoff.sln
sudo: required
install:
  - nuget install NUnit.Runners -Version 2.6.3 -OutputDirectory testrunner
  - nuget install coveralls.net -Version 0.6.0 -OutputDirectory coveralls
  - sudo apt-get install gtk-sharp2
  # install mono cecil
  - curl -sS https://api.nuget.org/packages/mono.cecil.0.9.5.4.nupkg > /tmp/mono.cecil.0.9.5.4.nupkg.zip
  - unzip /tmp/mono.cecil.0.9.5.4.nupkg.zip -d /tmp/cecil
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll .
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll /tmp/cecil/
  # install monocov
  - git clone --depth=50 git://github.com/csMACnz/monocov.git ../../csMACnz/monocov
  - cd ../../csMACnz/monocov
  - cp /tmp/cecil/Mono.Cecil.dll .
  - ./configure
  - make
  - sudo make install
  # return to source directory
  - cd ../../g8y3e/backoff-csharp
script:
  - export LD_LIBRARY_PATH=/usr/local/lib

  - xbuild /p:Configuration=Release backoff/GBackoff/GBackoff.sln
  - cd ./backoff/GBackoffTests/bin/Release/
  - ls -1
  - cd ../../../../
 
  - mono --profile=monocov:outfile=monocovCoverage.cov ./testrunner/NUnit.Runners.2.6.3/tools/nunit-console.exe ./backoff/GBackoffTests/bin/Release/GBackoffTests.dll
  - monocov --export-xml=monocovCoverage monocovCoverage.cov
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - mono ./coveralls/coveralls.net.0.6.0/csmacnz.Coveralls.exe --monocov -i ./monocovCoverage --repoToken "5BXSvdSTPJ1zesNUlAr4LVM52nw3iDsrA" --commitId $TRAVIS_COMMIT --commitBranch "$TRAVIS_BRANCH" --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci"  --useRelativePaths